steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:jdk21'
    env:
      - 'GOOGLE_RUNTIME_VERSION=21'
      - 'GOOGLE_FUNCTION_TARGET=in.tagme.hitown.bot.plugins.ApplicationKt'
      - 'GOOGLE_FUNCTION_SOURCE=.'
    args:
      - 'pack'
      - 'build'
      - 'gcr.io/$PROJECT_ID/tag-me-in-hi-town-bot'
      - '--builder'
      - 'gcr.io/google.com/cloudsdktool/cloud-sdk:jdk21'
      - '--path'
      - '.'

  - name: 'gcr.io/google-appengine/exec-wrapper'
    env:
      - 'GCLOUD_PROJECT=$PROJECT_ID'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'tag-me-in-hi-town-bot'
      - '--runtime'
      - 'java21'
      - '--trigger-http'
      - '--entry-point'
      - 'in.tagme.hitown.bot.plugins.ApplicationKt'
      - '--region'
      - 'africa-south1'
      - '--source=.'

images:
  - 'gcr.io/$PROJECT_ID/tag-me-in-hi-town-bot'
