[build]
builder = "gcr.io/buildpacks/builder:google-22"  # Or the latest google builder

[[env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "21"

[[env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "in.tagme.hitown.bot.plugins.ApplicationKt"

[[env]]
name = "GOOGLE_FUNCTION_SOURCE"
value = "."
